### PR TITLE
added flake8 and fixed any related errors

### PR DESCRIPTION
**Pull request by ipinak**

### CODE REVIEW

**Comment by lucasvfventura** [comment]
I think we should keep the name as props and not properties. Just to be more aligned with the .net and go implementation

**Comment by rogeralsing** [comment]
Agree with @lucasvfventura 
The name "Props" stems from Akka. and is a play on words. that "A movie actor needs props to act".

**Comment by ipinak** [comment]
I changed it because the linter complained, since the `props` is an already imported module. The other way to do is rename the imported module or ignore that error.

**Comment by alexpantyukhin** [comment]
@ipinak but context.py doesn't import `props` module now : https://github.com/AsynkronIT/protoactor-python/pull/22/files#diff-110bd9b3b64805e94eab7cf674520bbaR6. Or I missed something?

**Comment by ipinak** [comment]
@alexpantyukhin yes you are right I revert that back

**Pull request merged**
