### PR TITLE
Minor fixes & EventStream implementation

### PR DESCRIPTION
**Pull request by ipinak**
* fixes minor issues
    * adds NotImplementedError to prohibit implementation of a few base
    classes
    * adds an EventStream, DeadLetterEvent
    * publish DeadLetterEvents when sending user and system messages with a
    DeadLettersProcess
    * adds tests for the EventStream, which verify pub-sub work both for
    DeadLetterEvents and other types of messages

### CODE REVIEW

**Comment by rogeralsing** [comment]
This PR needs to be rebased.
@ipinak I've sent an invite for management rights of the repo too :-)

**Comment by ipinak** [comment]
I got the invite, thanks!. I will rebase this some time today. Hopefully ;)

**Comment by alexpantyukhin** [comment]
It brokes tests for me. I will fix.

**Comment by ipinak** [comment]
@alexpantyukhin I know I have a fix for it, which includes some additions for the `Context`.

**Pull request merged**
