### PR TITLE
fix process_registry tests

### PR DESCRIPTION
**Pull request by alexpantyukhin**
@ipinak Could you please verify this PR. It fixes broken tests.

### CODE REVIEW

**Comment by alexpantyukhin** [comment]
Yes, agree! I will fix it.

**Comment by alexpantyukhin** [comment]
@ipinak Fixed! Hopefully I have found all places.

**Comment by ipinak** [comment]
Perfect! Thanks.

**Comment by rogeralsing** [comment]
Ready to merge?

**Comment by ipinak** [comment]
@rogeralsing yes

**Pull request merged**
